[build]
  command = "" # no build, it's a static site
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://gogoworld-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pages/*"
  to = "/pages/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
